//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Win.IISService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IISService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllClients", ReplyAction="http://tempuri.org/IService1/SelectAllClientsResponse")]
        NorthWind.Entity.TbClienteBE[] SelectAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllClients", ReplyAction="http://tempuri.org/IService1/SelectAllClientsResponse")]
        System.Threading.Tasks.Task<NorthWind.Entity.TbClienteBE[]> SelectAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllProducts", ReplyAction="http://tempuri.org/IService1/SelectAllProductsResponse")]
        NorthWind.Entity.TbProductoBE[] SelectAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllProducts", ReplyAction="http://tempuri.org/IService1/SelectAllProductsResponse")]
        System.Threading.Tasks.Task<NorthWind.Entity.TbProductoBE[]> SelectAllProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NorthWind.Win.IISService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NorthWind.Win.IISService.IService1>, NorthWind.Win.IISService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NorthWind.Entity.TbClienteBE[] SelectAllClients() {
            return base.Channel.SelectAllClients();
        }
        
        public System.Threading.Tasks.Task<NorthWind.Entity.TbClienteBE[]> SelectAllClientsAsync() {
            return base.Channel.SelectAllClientsAsync();
        }
        
        public NorthWind.Entity.TbProductoBE[] SelectAllProducts() {
            return base.Channel.SelectAllProducts();
        }
        
        public System.Threading.Tasks.Task<NorthWind.Entity.TbProductoBE[]> SelectAllProductsAsync() {
            return base.Channel.SelectAllProductsAsync();
        }
    }
}
